StoneyJacksonOrg/collaborate

- LICENSE
> Fix the fifth word in line 13

- LICENSE
> Fixed the misspelling of software

- LICENSE
> Resolves #28

- LICENSE
Fixed the spelling of kinds on line 11. 
Issue #5
> Fix issue #5

- LICENSE
> Fixed the spelling of free on line 22

- LICENSE
> Fixed the spelling of work on line 114

- LICENSE
> Fixed line 652 word 4

- LICENSE
Fix mispelled word, "orcsdien" to "consider".
> Resolve Typo Line# 671

- LICENSE
Changed spelling of ruyo to your.
Fix issue #95
> Fix issue #95

- LICENSE
> Line 217 fixed misspelling of notices

- LICENSE
Change daded to added on line 218.
issue #93
> Fix issue #93

- LICENSE
> Line 363 corrected 'Lecneis' to read as License.

- LICENSE
> Line 62 'ttapense' to spell 'patents'.

- LICENSE
Fixed Issue #122 
Corrected "From"
> Resolved Issue #112

- LICENSE
Resolves Issue #111 
Corrected "Where"
> Fixed Issue #111

- LICENSE
> Fix mispelt word line 620

- LICENSE
> Fix line 35 mispelt word

- LICENSE
> Fix mispelt word line 526

- LICENSE
> Changed line 25

- LICENSE
> Changed line 484

- LICENSE
> Changed line 151

- LICENSE
Mispelled word "twih" in line 92 to correctly spelled word "with".
> Fixed Issue #199

- LICENSE
> Fix issue #174

- LICENSE
> Fix issue #175

- LICENSE
> Fix issue #198

- LICENSE
> Fix issue #205

- LICENSE
Changed mispelled word "xtteen" in line 107 to correctly spelled word
"extent".
> Fixed Issue #179

- LICENSE
Changed mispelled word "nlduice" in line 137 to correctly spelled word
"include".
> Fixed Issue #138

- LICENSE
Corrected "ifearb" to "breif" in line 635.
> Changed line 635
